### ISSUE TITLE
Travisser the "Page title missing"

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy-project.org#1]
![capture d ecran 2016-04-21 a 10 49 34](https://cloud.githubusercontent.com/assets/4503773/14703164/c3c5e55c-07ae-11e6-9aa0-7c42d7b93406.png)

Add a travis rule to avoid a page with missing title.

**Comment by ghost** [comment]
Since `--missing--` is a manually inserted placeholder for this alpha version, this should be verified on the user side (there will be a default title anyway).

**Comment by matthieu-lapeyre** [comment]
well it could raise a travis error to indicate to the user he has forgotten to put a title
