### ISSUE TITLE
Community projects pages are incomplete

### ISSUE THREAD

**Issue by ghost** [poppy-project/poppy-project.org#14]
- [x]  _Marionettes électriques_ page lacks Fr translation.
- [x]  _Cherry project_ should not refer to "us", since it's an external project; review is needed here.
- [x]  `description` front matter is missing on all projects pages.

**Comment by damiencaselli** [comment]
This should be done in [add_community_projects branch](/poppy-project/poppy-project.org/tree/add_community_projects).

**Comment by ghost** [comment]
19791bf resolves this.
