### ISSUE TITLE
"Technologies" page is incomplete

### ISSUE THREAD

**Issue by ghost** [poppy-project/poppy-project.org#17]
- [x] Some typos are still there.
- [x] Fr translation is missing.
- [x] front matter `description` is missing.

**Comment by jgrizou** [comment]
Arduino section is weird and content seems out of date. (Does this board worked in the end?)

Should we replace by Raspberry Pi and Arduino, or Onboard Electronics?

**Comment by jgrizou** [comment]
Do you agree to add hyper link for everything mentioned (e.g. V-rep, pypot, ...)?

**Comment by matthieu-lapeyre** [comment]
yep the electronics sections is outdated (and globally the technology section is...)

For the link, I do not know, it depends how many ? If there is a link by word it's bad, if it is 2/3 by section yes

**Comment by ghost** [comment]
The Arduino is outdated, so it should be removed.

As for the list of links, I think mentioning them once for all somewhere in the website is fine. This page seems the right place to do it.

**Comment by ghost** [comment]
@jgrizou I couldn't properly translate some stuff to French, do you mind helping with this please?

https://github.com/poppy-project/poppy-project.org/blob/master/_pages/technologies/en.html#L44 :

> Within a small form factor, these motors embed high-precision monitoring and control and are synchronized on a shared communication and power line.

**Comment by jgrizou** [comment]
Oui pas simple du tout celle-là! Tentative: 

> De taille compacte, très précis et réactifs, ces moteurs ont l'avantage d'être connectable en série sur un bus distribuant à la fois puissance et communication.

Je jetterai un oeil plus précis aux nouvelles pages _en_ et _fr_ plus tard dans la semaine.

**Comment by ghost** [comment]
@jgrizou did you manage to think of a proper translation for this?

**Comment by jgrizou** [comment]
Yes I ma pretty sire I replied somewhere many fays ago

**Comment by ghost** [comment]
I'm unsure of that "somewhere" 😃 
Could you please repost your suggestions here?

**Comment by jgrizou** [comment]
Sorry I was on cellphone responding in a hurry. I proposed a translation just above (copied below), and you thumbed it up. Are we talking about the same thing?

> De taille compacte, très précis et réactifs, ces moteurs ont l'avantage d'être connectable en série sur un bus distribuant à la fois puissance et communication.

**Comment by ghost** [comment]
Ah never mind, that "Je jetterai un oeil plus précis aux nouvelles pages en et fr plus tard dans la semaine." lead me to think that was juste a draft, even though that looked perfect to me.
I'll integrate these changes.

**Comment by ghost** [comment]
Fixed by 9eff5ee

**Comment by jgrizou** [comment]
Yep j'ai pas eu le temps de relire les pages encore..
